### PR TITLE
Move docs to /docs

### PR DESCRIPTION
**Pull request by Cretezy**
This change is so the project's manager can go in the repos settings and activate Github Pages with the /docs option, making the documentation available at https://polidea.github.io/react-native-ble-plx/

Example on my fork: https://cretezy.github.io/react-native-ble-plx/

### CODE REVIEW

**Comment by Cierpliwy** [comment]
Thanks for your effort! It looks good except automatic part. I think that BLE configuration should be done manually as there are few steps to consider based on your needs.

**Comment by Cretezy** [comment]
The automatic part covers about 80% of use cases. I think it's a good middle ground between ease of use and complexity.

**Comment by Cierpliwy** [comment]
In that case I think user should know which steps needs to manually performed. Could you add notes about that in this PR?

**Comment by Cretezy** [comment]
I've added the step (android permission) which must be done manually. The rest should be automatic.

**Pull request merged**
