### PR TITLE
Add `<React/` prefix to React imports

### PR DESCRIPTION
**Pull request by iegik**

### CODE REVIEW

**Comment by mmerickel** [comment]
I can confirm that this fixes my issues on react-native 0.48.1.

**Comment by chemdrew** [comment]
fixes my issues with building in xcode 9 beta. Any eta on getting this in a patch update?

**Comment by fisehara** [comment]
I was facing duplicate definitions and protocols. Fixed with <React/ prefix in file BleClient.h

**Comment by kaldebert** [comment]
+1

**Pull request merged**
