### PR TITLE
Added a method to enable / disable bluetooth [android / ios] 

### PR DESCRIPTION
**Pull request by watadarkstar**
Adds a method to enable / disable bluetooth. Closes: #31 

**Tasks:**

- [ ] Implement Android code
- [ ] Implement JS code
- [ ] Implement example code
- [ ] Write tests
- [ ] Ensure flow types are created 
- [ ] Write documentation

**Test check list:**

- [x] Ran `yarn`
- [ ] Ran `yarn docs`
- [ ] Passed all tests with `yarn test`
- [ ] Ran `yarn prettier`
- [ ] Ran `yarn lint`
- [ ] Tested in example app

### CODE REVIEW

**Comment by fmaturel** [comment]
Definitely need this feature, when do you plan to merge this?

**Comment by watadarkstar** [comment]
> Make enable/disable functions Promises as they are implemented asyncronously on Android

Sounds good.

> Consider extending behaviour by enabling directly, via intent, by suggesting settings page.

I thought about this too. Since iOS won't be able to enable / disable bluetooth automatically like Android, do we want to:

1. Enable and disable bluetooth on Android, but on iOS open the settings screen. The problem with this is its inconsistent and might be confusing to the developer / user.
2. Or do we open the settings screen for Android and iOS. The problem with this approach is that you can open the settings screen on iOS, but I don't believe you can directly open the bluetooth settings page. And at this point does it even make sense to call the public API methods: `disableBluetooth / enableBluetooth` when it opens the settings screen on both Android and iOS.
3. Lastly, on iOS we don't support `enableBluetooth / disableBluetooth` and we instead throw an error like you said.

I think the best approach would be to enable and disable bluetooth on Android and throw an error on iOS, but I'm up for a discussion. What do you think @Cierpliwy @DariuszAniszewski ?

> Make sure that Flow types are created and documentation is generated explaining implemented behaviour.

Added the flow types to the checklist above. Implementing documentation was already on the TODO list.

**Comment by Cierpliwy** [comment]
> Also do you want to rename enableBluetooth() to enable() etc.? I went with enableBluetooth so it was clear what enable was enabling, but I'm for suggestions as I was torn on what the public API names should be.

There is already `state()` function so `enable()` and `disable()` is definitely not out of place.

> I think the best approach would be to enable and disable bluetooth on Android and throw an error on iOS and leave it up to the developer to handle this case, but I'm up for a discussion.

Initially I was thinking about:

| func                               | iOS                                |                     Android |
| -----------------------------------|------------------------------------|-----------------------------|
| disableBluetooth()                 | Error                              | Success(BleManager) / Error |
| enableBluetooth()                  | Error                              | Success(BleManager) / Error |
| enableBluetooth(ShowNativeDialog)  | Error or custom dialog             | Intent                      |
| enableBluetooth(GoToSettingsPage)  | Go to main settings / BLE settings | Go to BLE settings          |

but this could be:

| func                               | iOS                                |                     Android |
| -----------------------------------|------------------------------------|-----------------------------|
| disable()                          | Error                              | Success(BleManager) / Error |
| enable()                           | Error                              | Success(BleManager) / Error |
| enable(false)                      | Error or custom dialog             | Intent                      |
| openSettings()                     | Go to main settings / BLE settings | Go to BLE settings          |

where 2nd function is defined as `function enable(showNativeDialog: boolean = false)`.

**Comment by watadarkstar** [comment]
> There is already state() function so enable() and disable() is definitely not out of place.

Agreed. I will rename it to enable / disable.

> but this could be:

I like this a lot more. However, I would simplify it like this:

func | iOS | Android
------------ | ------------- | -------------
disable() | Error | Success(BleManager) / Error
enable() | Error | Success(BleManager) / Error
openSettings() | Go to main settings / BLE settings | Go to BLE settings

**Thoughts:**

The reason I'm not a fan of having `showNativeDialog: boolean = false` is for the following reasons:

- Its trivial to implement a confirmation dialog that prompts the user to enable bluetooth for a developer. It seems like extra overhead in this library, when the developer can do this easily.
- This library is not a UI library it should not dictate what the user experience is, the developer / designer should determine that. 

To me its easy for a developer to write a native dialog like so and I would encourage them to do this, but its unnecessary to include this behaviour in this library. If they want this behaviour they can simply do:

```javascript
// Works on both iOS and Android
Alert.alert(
  'Enable bluetooth?',
  'Are you sure you want to enable bluetooth.',
  [
    {text: 'Yes', onPress: () => ble.enable()}, // <----------------------- calls enable()
    {text: 'No', onPress: () => console.log('No Pressed')},
  ]
)
```

What do you think as after all this is your library? :)

**Comment by Cierpliwy** [comment]
I think this is reasonable. Still we should inform user that he/she is obligated to show alert if he/she enables or disables bluetooth automatically.

On iOS I think we could open BLE settings by calling:
`UIApplication.shared.open(URL(string:"App-Prefs:root=Bluetooth")!, ...)`
However path depends on iOS version so there will be big switch case ;)

**Comment by watadarkstar** [comment]
@Cierpliwy Okay sounds good. I will work on this over the weekend.

**Comment by watadarkstar** [comment]
@Cierpliwy Do you get this error when running `yarn test`?

```
 FAIL  __tests__/BleManager.js
  ● Test suite failed to run

    Cannot find module 'NativeModules' from 'react-native-implementation.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:191:17)
      at Object.get NativeModules [as NativeModules] (node_modules/react-native/Libraries/react-native/react-native-implementation.js:108:32)
      at Object.<anonymous> (src/BleModule.js:548:45)
```

Versions:

```
react-native-cli@2.0.1
node@v8.1.1
yarn@1.0.2
```

**Comment by Cierpliwy** [comment]
Everything works fine for me. `NativeModules` is react-native dependency:
`import { NativeModules } from 'react-native';`
Are you sure that your RN version is installed properly?

**Comment by watadarkstar** [comment]
@Cierpliwy 

I think so. I did `npm install -g react-native-cli`. And when running `react-native -v` inside the root of this project I get:

```
$ react-native -v                                                                                                               
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory
```

The `react-native: n/a - not inside a React Native project directory` might be the reason? I don't know why its not detecting the project as a react native project. Any ideas?

**Comment by watadarkstar** [comment]
@Cierpliwy In this commit https://github.com/Polidea/react-native-ble-plx/pull/139/commits/fa108b57ba4afda45182c4b8dc0dd22d4b6108af I moved the jest config found in `package.json` into its own file. The reason I did this:

- If you run `cd examples/ReactBLEScanner` and then `yarn install` you will get the following error when you run `yarn test` from the root of this project. The error says that there are two `node_modules` with `react-native` (one in the root project and one in examples/ReactBLEScanner) and cannot resolve which one to use. So in the jest config I ignore the one in examples/ReactBLEScanner/node_modules. @Cierpliwy you probably never ran into this issue because you never tried running the example and then running `yarn test` from the root of this project.

```
 FAIL  __tests__/BleManager.js
  ● Test suite failed to run

    The name `setupDevtools` was looked up in the Haste module map. It cannot be resolved, because there exists several different files, or packages, that provide a module for that particular name and platform. The platform is generic (no extension). You must delete or blacklist files until there remains only one of these:
    
      * `/Users/adriancarolli/workspace/react-native/react-native-ble-plx/examples/ReactBLEScanner/node_modules/react-native/Libraries/Devtools/setupDevtools.js` (module)
      * `/Users/adriancarolli/workspace/react-native/react-native-ble-plx/node_modules/react-native/Libraries/Core/Devtools/setupDevtools.js` (module)
```
- I also only look for `__tests__` inside the root directory. I did this because it will make jest faster and not try to run `__tests__` outside of this project i.e. in the examples/ReactBLEScanner folder. They do this in the `react` repo at Facebook so its pretty reasonable:

https://github.com/facebook/react/blob/d7f6ece27cb7cde67ef0e9c9aea4669f873ddab3/scripts/jest/config.source.js#L16-L17

**Comment by watadarkstar** [comment]
@Cierpliwy Now that I'm reading more about the Android `enable()` bluetooth documentation and what people are saying about it [here](https://stackoverflow.com/questions/6546083/how-to-turn-on-bluetooth-on-button-click) 

The docs say:

> Bluetooth should never be enabled without direct user consent. If you want to turn on Bluetooth in order to create a wireless connection, you should use the ACTION_REQUEST_ENABLE Intent, which will raise a dialog that requests user permission to turn on Bluetooth. The enable() method is provided only for applications that include a user interface for changing system settings, such as a “power manager” app.
> 
> So it's not suitable for you to turn on Bluetooth by the method enable() unless you make the user know what you will do.

Maybe we should make it the default behaviour to request permissions given what it says above ^

**Comment by watadarkstar** [comment]
@Cierpliwy I am trying to run `examples/ReactBLEScanner` and I want it to use my local copy of `react-native-ble-plx` for testing purposes. I tried adding this to package.json:

```
"react-native-ble-plx": "../../"
```

But then I run into all kinds of issues. How do you usually test locally when testing native code changes for `react-native-ble-plx`?

**Comment by Cierpliwy** [comment]
> If you run cd examples/ReactBLEScanner and then yarn install you will get the following error when you run yarn test from the root of this project. 

I would bother with ReactBLEScanner as there is a separate task to remove it and rewrite it (#189). It's currently in progress and @jerzyKleszcz is taking care of it. Please remove any changes to ReactBLEScanner in this PR.

> Maybe you're right we should make it the default behaviour to request permissions given what it says above ^ I don't know I'm on the fence.

I think that requesting permissions is a job of [another library](https://github.com/yonahforst/react-native-permissions). 

We can also create special `requestEnable` function which uses Intent to enable Bluetooth. Unfortunately there isn't such thing as `requestDisable`. Still I want pure `enable` and `disable` functions to be available.

**Comment by watadarkstar** [comment]
Unfortunately, I just don't have time to work on this. Additionally, the Expo team at Facebook is working on a bluetooth API for react native: https://expo.canny.io/feature-requests/p/bluetooth-api

**Pull request closed without merging**
