### PR TITLE
Change const enums to simple enums

### LINKED ISSUE #537: Remove const enums from index.d.ts do it works with --isolatedModules
## Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

## Expected Behavior

There should be no typescript errors with --isolatedModules, which is recommended for react-native typescript since typescript const enums don't work with babel

## Current Behavior

Currently, every enum on index.d.ts is defines as a `const enum`. These are not compatible with `--isolatedModules`(see microsoft/Typescript#207). However, babel does not support const enums (babel/babel#8741) which means that when writing RN projects with typescript, using `--isolatedModules` guarantess the programmers won't accidentally add in const enums and break code unknowingly.

In practice, react-native-ble-plx doesn't actually *use* typescript const enums(which is what is declared in the .d.ts), which means that it's fine to run the library without isolatedmodules since we're not really compiling typescript through babel; However, this particular change creates a conflict when using that particular option at no real benefit from what I can gather.

### Steps to Reproduce

write any code with `isolatedModules` enabled on `tsconfig.json`, and you'll see that your IDE(if it uses the ts language server) will complain when using ble-plx enums.

### PR DESCRIPTION
**Pull request by Barbiero**
Closes #537

### CODE REVIEW

**Comment by dariuszseweryn** [comment]
Hello @Barbiero 
To incorporate your changes we would need you to sign our Contributor License Agreement as mentioned in the post above.
Thank you!

**Comment by jfamousket** [comment]
How is this going because at the moment we need this for some of our typescript guards to work. We changed it manually but it is really a pain to always remember to change it when we reinstall packages. Would be great if this request is reviewed and merged.

**Comment by dariuszseweryn** [comment]
Hello,
Sorry for such a delay. We are now doing some work with extracting the core of this library to be shared with our flutter lib. Once that is completed we will continue proceeding with this PR which is at this point ready to be merged. Sorry for waiting.

**Comment by piotrdubiel** [comment]
Bump

**Comment by ScreamZ** [comment]
@dariuszseweryn, can we expect this to be merged ?

**Comment by ScreamZ** [comment]
@Cierpliwy Feel free to ping me when a new release has been deployed on npm :p Thank you very much

**Comment by Cierpliwy** [comment]
1.1.1 is online :) @ScreamZ

**Comment by ScreamZ** [comment]
Awesome, thanks

**Pull request merged**
