### PR TITLE
Send event when device is disconnected

### LINKED ISSUE #663: [Android] v2.0.0 seems to ignore onDeviceDisconnected callback
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

## Behavior

I decided to update my app to RN 0.62, and with that came the react-native-ble-plx update to 2.0.

However, after updating I noticed that the `onDeviceDisconnected` callback is getting ignored, no changes made to the actual code; with BLE-PLX v1.1.0 it was working fine. Changelog makes no mention of this behavior change, but it does mention changing the multiplatform ble adapter. Maybe there's something missing there?

I'm not sure how to help diagnose this behavior. To reproduce, try to disconnect an external BLE device after connecting (via `BleManager#connectToDevice`) and register said device with a onDisconnect callback (either via `BleManager#onDeviceDisconnected` or `Device#onDisconnected`).

I have not tested this on iOS.

### LINKED ISSUE #673: Unable to detect connection lost in-between, It seems like method  onDeviceDisconnected not been call.
scenario I am following.
1. Made a connection with device inside the mobile application.
2. After some time to detect disconnection, I just powered off of ble device.
3. Application should detect disconnection in that case too.
4. please check scanAndConnect method, inside that i am using disconnection listener, and guide me to implement this please. 
my code script which is now working. no error no nay message. It's been ignored i guess.
`
async scanAndConnect() {
        this.setState({text1:"Scanning..."})
        this.manager.startDeviceScan(null, null, (error, device) => {
            console.log("Scanning...");
            if (null) {
                console.log('null')
            }
            if (error) {
                this.alert("Error in scan=> "+error)
                this.setState({text1:""})
                this.manager.stopDeviceScan();
                return
            }
            if( /[_]/g.test( device.name ) ) 
            {
                let nameSplit = device.name.split('_');
                if(nameSplit[0] == 'mydevice'){
                    const serviceUUIDs= device.serviceUUIDs[0]
                    this.setState({text1:"Connecting to "+device.name, deviceName : device.name})
                    this.manager.stopDeviceScan();
                    //***********listener for disconnection
                   this.BleManager.onDisconnected(this.state.deviceid, (error, device) => {
                       console.log(error)
                       console.log('DisConnected ' + new Date().toISOString());
                  })
                    //***********listener for disconnection
                    this.manager.connectToDevice(device.id, {autoConnect:true}).then((device) => {
                        (async () => {
                            const services = await device.discoverAllServicesAndCharacteristics()
                            const characteristic = await this.getServicesAndCharacteristics(services)
                            this.setState({"deviceid":device.id, serviceUUID:serviceUUIDs, characteristicsUUID : characteristic.uuid,device:device })
                            this.setState({text1:"Conneted to "+device.name})
                        })();
                        this.setState({device:device})
                        return device.discoverAllServicesAndCharacteristics()
                    }).then((device) => {
                         return this.setupNotifications(device)
                    }).then(() => {
                        console.log("Listening...");
                    }, (error) => {
                        this.alert("Connection error"+JSON.stringify(error))
                    })
                }
            }
       });
    }

`

### LINKED ISSUE #675: onDeviceDisconnected doesn't detect lost connection to device
## Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior

after connecting to device, i try to disable bluetooth or disconnect my device for example.
onDeviceDisconnected should intercept this behaviour and alert me wehenver im disconnected.
## Current Behavior
onDeviceDisconnected  is never fired
**this also apply to onDisconnected**
>   this.manager.onDeviceDisconnected(device.id, (error, device) => {
>               if (error) {
>                 console.log(error);
>               }
>               console.log('Device is disconnected');
>             });

the console log is never shown

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. connect to a device
2.  try to interrupt the connection(close bluetooth, disconnect your device..)
3. check if onDeviceDisconnected output something 

### Context

* Library version: 2.0.0
* Platform: Android.
* react native :0.62

here is what my function look like:
```js
 scanAndConnect() {
    this.manager.startDeviceScan(null, null, (error, device) => {
      if (error) {
        return;
      }
      if (device.id === '61:A9:15:96:3D:2C') {
        this.manager.stopDeviceScan();
        device
          .connect()
          .then(device => {
            this.manager.onDeviceDisconnected(device.id, (error, device) => {
              if (error) {
                console.log(error);
              }
              console.log('Device is disconnected');
            });
            return device.discoverAllServicesAndCharacteristics();
          })
          .then(device => {
            // Do work on device with services and characteristics
          })
          .catch(error => {
            console.log('errr ', error);
          });
        // Proceed with connection.
      }
    });
  }
```

### PR DESCRIPTION
**Pull request by mikolak**
This should fix the 3 linked issues, but I have no means to test it right now, hence the draft.

Fixes #663 
Fixes #673 
Fixes #675

### CODE REVIEW

**Comment by Barbiero** [comment]
This is working great for me. Thank you!

when a new version is published I'll ve sure to upgrade.

**Comment by josef256** [comment]
this is also working for me.  thanks for fixing the issue.

**Comment by josef256** [comment]
hello,
any ETA whene the fix will be up ?

**Comment by dariuszseweryn** [comment]
It is fixed on `2.0.1`

**Pull request merged**
